// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtYGoZ3Yrvzv1jjVBmubuFqmo7BSXOK8Y',
    appId: '1:498422502310:web:aa1d9a88692b8b015bf567',
    messagingSenderId: '498422502310',
    projectId: 'noteapp-3606d',
    authDomain: 'noteapp-3606d.firebaseapp.com',
    storageBucket: 'noteapp-3606d.appspot.com',
    measurementId: 'G-9VPEKHXNPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGe4hnj3WfE0N67_XMDF8MLSvon3Xole0',
    appId: '1:498422502310:android:efee1c2f2576b0f65bf567',
    messagingSenderId: '498422502310',
    projectId: 'noteapp-3606d',
    storageBucket: 'noteapp-3606d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhKtj94epmeoJ_XbuSQdh12TqkwzE58_8',
    appId: '1:498422502310:ios:977bc63ca1da62435bf567',
    messagingSenderId: '498422502310',
    projectId: 'noteapp-3606d',
    storageBucket: 'noteapp-3606d.appspot.com',
    iosClientId: '498422502310-aubep6rkikrubp19vocl598q72desndg.apps.googleusercontent.com',
    iosBundleId: 'inv.thugbn.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhKtj94epmeoJ_XbuSQdh12TqkwzE58_8',
    appId: '1:498422502310:ios:977bc63ca1da62435bf567',
    messagingSenderId: '498422502310',
    projectId: 'noteapp-3606d',
    storageBucket: 'noteapp-3606d.appspot.com',
    iosClientId: '498422502310-aubep6rkikrubp19vocl598q72desndg.apps.googleusercontent.com',
    iosBundleId: 'inv.thugbn.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtYGoZ3Yrvzv1jjVBmubuFqmo7BSXOK8Y',
    appId: '1:498422502310:web:b541b231481116635bf567',
    messagingSenderId: '498422502310',
    projectId: 'noteapp-3606d',
    authDomain: 'noteapp-3606d.firebaseapp.com',
    storageBucket: 'noteapp-3606d.appspot.com',
    measurementId: 'G-WVJ1QQNRQQ',
  );
}
