const darkMaterial = {
  "colorScheme": {
    "onSurface": "#FFFFFF",
    "onBackground": "#FFFFFF",
    "onPrimary": "#FFFFFF",
    "onSecondary": "#FFFFFF",
    "onSurfaceVariant": "#FFFFFF",
    "onBackgroundVariant": "#FFFFFF",
    "onTertiary": "#FFFFFF",
    "onTertiaryContainer": "#FFFFFF",
    "onError": "#FFFFFF",
    "onErrorContainer": "#FFFFFF",
    "surface": "#1C1B1F",
    "background": "#1C1B1F",
    "primary": "#FFFFFF",
    "primaryContainer": "#FFFFFF",
    "secondary": "#FFFFFF",
    "secondaryContainer": "#FFFFFF",
    "tertiary": "#FFFFFF",
    "tertiaryContainer": "#FFFFFF",
    "error": "#FFFFFF",
    "errorContainer": "#FFFFFF",
    "outline": "#FFFFFF",
    "outlineVariant": "#FFFFFF",
    "shadow": "#FFFFFF",
    "surfaceTint": "#FFFFFF",
    "inverseSurface": "#1C1B1F",
    "inverseOnSurface": "#FFFFFF",
    "inversePrimary": "#FFFFFF",
    "surfaceVariant": "#FFFFFF",
    
  }
};

const lightMaterial = {
  "colorScheme": "#000000",
    "onSurface": "#000000",
    "onBackground": "#000000",
    "onPrimary": "#000000",
    "onSecondary": "#000000",
    "onSurfaceVariant": "#000000",
    "onBackgroundVariant": "#000000",
    "onTertiary": "#000000",
    "onTertiaryContainer": "#000000",
    "onError": "#000000",
    "onErrorContainer": "#000000",
    "surface": "#FFFFFF",
    "background": "#FFFFFF",
    "primary": "#000000",
    "primaryContainer": "#000000",
    "secondary": "#000000",
    "secondaryContainer": "#000000",
    "tertiary": "#000000",
    "tertiaryContainer": "#000000",
};